homepage:
    path: /
    controller: App\Controller\DashboardHomePageController::displayDashboardHomePage

addNewTransaction:
    path: /ajouter-transaction
    controller: App\Controller\AddNewTransactionController::displayAddNewTransactionPage

removeTransaction:
    path: /supprimer-transaction
    controller: App\Controller\RemoveTransactionController::displayRemoveTransactionPage

testGraphique:
    path: /graphique-gains
    controller: App\Controller\GraphController::displayGraphEarningsPage